@php($title = "Anatomy and Function of the Heart’s Electrical System | Bombay Hospital Indore")
@section('meta_desc') @endsection

@extends('layouts.default')
@section('content')

<!-- BREADCRUMB
			============================================= -->
<div id="breadcrumb" class="division">
    <div class="container">
        <div class="row">
            <div class="col">
                <div class=" breadcrumb-holder">

                    <!-- Breadcrumb Nav -->
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{ route('home')}}">Home</a></li>
                            <li class="breadcrumb-item"><a href="#">Health Education</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Cardiology
                            </li>
                        </ol>
                    </nav>

                    <!-- Title -->
                    <h4 class="h4-sm steelblue-color">Anatomy and Function of the Heart’s Electrical System</h4>

                </div>
            </div>
        </div> <!-- End row -->
    </div> <!-- End container -->
</div> <!-- END BREADCRUMB -->

<div id="department-page" class="wide-60 department-page-section division">
    <div class="container">
        <div class="row">


            <!-- DEPARTMENT DETAILS -->
            <div class="col-lg-12">
                <div class="txt-block pr-30">

                    <!-- CONTENT BLOCK -->
                    <div class="content-block mb-40">
                        <h5 class="h5-md steelblue-color">The heart’s electrical system</h5>
                        <p>The heart is, in the simplest terms, a pump made up of muscle tissue. Like all muscle, the
                            heart requires a source of energy and oxygen in order to function. The heart’s pumping
                            action is regulated by an electrical conduction system that coordinates the contraction of
                            the various chambers of the heart.</p>

                        <h5 class="h5-md steelblue-color">How does the heart beat?</h5>
                        <p>An electrical stimulus is generated by the sinus node (also called the sinoatrial node, or SA
                            node). This is a small mass of specialized tissue located in the right atrium (right upper
                            chamber) of the heart. The sinus node generates an electrical stimulus regularly (60 to 100
                            times per minute under normal conditions). The atria are then activated. The electrical
                            stimulus travels down through the conduction pathways (similar to the way electricity flows
                            through power lines from the power plant to your house) and causes the heart’s ventricles to
                            contract and pump out blood. The right and left atria (the two upper chambers of the heart)
                            are stimulated first and contract for a short period of time before the right and left
                            ventricles (the two lower chambers of the heart).</p>

                        <p>The electrical impulse travels from the sinus node to the atrioventricular node (also called
                            AV node). There, impulses are slowed down for a very short period, then continue down the
                            conduction pathway via the bundle of His into the ventricles. The bundle of His divides into
                            right and left pathways to provide electrical stimulation to the right and left ventricles.
                        </p>

                        <p>Normally at rest, as the electrical impulse moves through the heart, the heart contracts
                            about 60 to 100 times a minute, depending on a person’s age.</p>

                        <p>Each contraction of the ventricles represents one heartbeat. The atria contract a fraction of
                            a second before the ventricles so their blood empties into the ventricles before the
                            ventricles contract.</p>
                    </div> <!-- END CONTENT BLOCK -->
                </div>
            </div> <!-- END DEPARTMENT DETAILS -->

        </div> <!-- End row -->
    </div> <!-- End container -->
</div>

@stop